name: CI
on:
  push:
    branches:
      - master
  schedule:
    - cron '0 0 * * *'

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: apt install -y gcc make autoconf g++ texinfo libmpfr-dev libgmp-dev wget bzip2 git xz-utils sudo libmpc-dev zlib1g-dev bison flex gawk autopoint libtool fakeroot mount parted gettext
    - run: bash download.sh
    - run: bash bootstrap.sh
    - run: bash compile.sh
